# Paths
source:      ./app
destination: ./dist

# Setup
name: Per SandstrÃ¶m
permalink: /blog/:year/:month/:title/
exclude:
 - autoprefixer.yml

# Posts
paginate: 9
paginate_path: "blog/page:num"

# Dependecies
gems:
  - sass
  - compass
  - breakpoint
  - autoprefixer-rails
  - uglifier
  - jekyll-assets
  - jekyll-assets/compass
  - jekyll-sitemap

# Jekyll Assets configuration
# https://github.com/ixti/jekyll-assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vendor
  js_compressor:  uglifier
  css_compressor: sass

# Variables
mixpanel_token: 2622507bdf0bea0ad966ba92c55ec5a9
